version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: commander
    versions:
    - 6.2.1
    - 7.0.0
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: inquirer
    versions:
    - 7.3.3
